"""
Django settings for broadcast project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xvq***!bskbq*2m_!nu4*0=hs5i=i2#q99^oj2&146)@ss-v2u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# settings.py

LANGUAGE_CODE = 'uk'  # Встановлюємо українську мову як основну

TIME_ZONE = 'Europe/Kyiv' # Ваш часовий пояс

USE_I18N = True  # Вмикаємо інтернаціоналізацію

USE_L10N = True  # Вмикаємо форматування дат, чисел відповідно до локалі

USE_TZ = True    # Вмикаємо підтримку часових поясів
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    "*",
    'test.shtoma.top',
]

# Публічний Jitsi‑домен
JITSI_DOMAIN = os.getenv(
    'JITSI_DOMAIN',
    'meet.jit.si'
)

# Дозволяємо CSRF для обох https‑доменів
CSRF_TRUSTED_ORIGINS = [
    'https://test.shtoma.top',
    "https://localhost:8000",
    "http://localhost:8000",
    "http://0.0.0.0:8000",
    "http://127.0.0.1:8000",
]

# production safety
SECURE_SSL_REDIRECT = False              # Django всегда редиректит на https

AUTH_USER_MODEL = 'users.User'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'users',
    'chat',
    'meetings',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE    = False
ROOT_URLCONF = 'broadcast.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'broadcast' / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'broadcast.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_ROOT = BASE_DIR / 'staticfiles'
INSTALLED_APPS += ["widget_tweaks"]
# Медіа (для uploads, attachments, записів)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

ASGI_APPLICATION = 'broadcast.asgi.application'
REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379')
CHANNEL_LAYERS = {
    'default': {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
        # "CONFIG": {
        #     "hosts": [("127.0.0.1", 6379)],
        # },
    },
}
X_FRAME_OPTIONS = 'ALLOWALL'
from django.urls import reverse_lazy

LOGIN_REDIRECT_URL = reverse_lazy('meetings:list')
LOGOUT_REDIRECT_URL = reverse_lazy('users:login')
LOGIN_URL = reverse_lazy('users:login')

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0' # Для зберігання результатів завдань (опціонально)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Kiev' # Встановіть вашу часову зону
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60 # Таймаут завдання, наприклад 30 хвилин

# Для Django Email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'maksym.putin.django@gmail.com'
EMAIL_HOST_PASSWORD = 'lwoc lcnb cbxj iyof'
EMAIL_USE_TLS = True