# Generated by Django 5.1.7 on 2025-04-18 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Слаг')),
                ('is_private', models.BooleanField(default=False, verbose_name='Приватний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='chatrooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Кімната',
                'verbose_name_plural': 'Кімнати',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='Текст повідомлення')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat_files/', verbose_name='Файл')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Час відправки')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Повідомлення',
                'verbose_name_plural': 'Повідомлення',
                'ordering': ('timestamp',),
            },
        ),
    ]
