# Generated by Django 5.1.7 on 2025-05-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatroom_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
