# Generated by Django 5.1.7 on 2025-04-18 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Тема зустрічі')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('room_name', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Назва кімнати')),
                ('scheduled_time', models.DateTimeField(verbose_name='Заплановано на')),
                ('duration', models.PositiveIntegerField(default=60, verbose_name='Тривалість (хвилин)')),
                ('recording_enabled', models.BooleanField(default=False, verbose_name='Увімкнути запис')),
                ('recording_url', models.URLField(blank=True, verbose_name='URL запису')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Організатор')),
                ('participants', models.ManyToManyField(blank=True, related_name='meetings', to=settings.AUTH_USER_MODEL, verbose_name='Учасники')),
            ],
            options={
                'verbose_name': 'Зустріч',
                'verbose_name_plural': 'Зустрічі',
                'ordering': ['-scheduled_time'],
            },
        ),
    ]
