# Generated by Django 5.1.7 on 2025-05-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_alter_meeting_jitsi_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID завдання Celery'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Нагадування відправлено'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='jitsi_room',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='Jitsi room'),
        ),
    ]
